### ISSUE TITLE
Not able to connect to the websocket

### ISSUE THREAD

**Issue by auoldariu69** [Elektordi/obs-websocket-py#73]
When trying to connect to my websocket, using the `switch_scene.py` sample im getting this error: 

`INFO:obswebsocket.core:Connecting...
INFO:obswebsocket.core:Connected!
Traceback (most recent call last):
  File "c:\Users\.\development\testing\python\obspython\main.py", line 19, in <module>
    ws.connect()
  File "C:\Users\.\AppData\Local\Programs\Python\Python39\lib\site-packages\obswebsocket\core.py", line 70, in connect
    self._auth(self.password)
  File "C:\Users\.\AppData\Local\Programs\Python\Python39\lib\site-packages\obswebsocket\core.py", line 116, in _auth
    if result['status'] != 'ok':
KeyError: 'status'`

this is my obs-websocket settings page: 
![image](https://user-images.githubusercontent.com/91834527/150876972-f9defe09-efef-438b-8b0f-26c7ea515605.png)

thanks in advance

**Comment by abrasher** [comment]
I had the same issue. You have obs-websocket 5.0.0 installed and this library is not updated to that version yet. Downgrade to obs-websocket 4.9.1
